app:
  gateway:
    url: ${게이트웨이 주소}

spring:
  application:
    name: memo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db 주소}
    username: ${db 사용자}
    password: ${db 암호}

  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true
      secrets:
        enabled: true

  kafka:
    consumer:
      bootstrap-servers: ${카프카 서버 주소}:9092
    producer:
      bootstrap-servers: ${카프카 서버 주소}:9092

openapi:
  service:
    url: ${게이트웨이 주소}

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    enabled: false