server:
  port: 8090

spring:
  application:
    name: memo

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #??? ??

  profiles:
    include: oauth

jwt:
  secret: ${JWT_SECRET_KEY}

springdoc:
  api-docs:
    path: /memo-api/v3/api-docs
  swagger-ui:
    path: /memo-api/v3/swagger-ui.html

---
spring:
  profiles:
    active: dev, prod