server:
  port: 8090

spring:
  application:
    name: memo
  datasource:
    #    url: jdbc:h2:tcp://localhost/~/withsafe
    #    username: sa
    #    password: 1
    #    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.212.76/meeton?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: '1918'


  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #??? ??

  profiles:
    include: oauth

jwt:
  secret: /vUwAz/Vx78zX5/E4v6kjfbyoTRpYtOK2WT9rYcXeNPzDMuv1BlehYL113paVVYvUTyUIYg3kSZglWjEAJxgMw==

springdoc:
  api-docs:
    path: /memo-api/v3/api-docs
  swagger-ui:
    path: /memo-api/v3/swagger-ui.html

openapi:
  service:
    url: http://172.16.212.76:8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://172.16.212.76:8761/eureka

  instance:
    hostname: 172.16.212.76
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}